version: "3.4"
services:
  tethealla:
    build:
      context: .
      labels:
        com.example.description: "Tethealla PSOBB Server"
    ports:
      - "11000:11000"
      - "11001:11001"
      - "12000:12000"
      - "12001:12001"
      - "5278:5278"
      - "5279:5279"
      - "5280:5280"
    volumes:
      - psobb-data:/server
  mariadb:
    image: mariadb:10.3
    hostname: psobb-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    ports:
      - 3306:3306
    volumes:
      - psobb-db:/var/lib/mysql
volumes:
    psobb-db:
    psobb-data:
